[package]
name = "json-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
serde_json = "1.0"
minify = "1.3.0"
linked-hash-map = "0.5.6"
serde = "1.0.195"
